version: '3'

services:
  app:
    image: 'app.jar'
    build: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/new_year_toys
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=7410
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:10'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=7410
      - POSTGRES_USER=postgres
      - POSTGRES_DB=new_year_toys